name: Build

on:
  - push
  - pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    strategy:
      matrix:
        python-version: [ '3.12' ]
    name: Build
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: SanctumLabs/ci-workflows/.github/workflows/python-build.yml@main
    with:
      command: make build
      python-version: ${{ matrix.python-version }}
      packager: poetry
