name: Tests

on:
  - push
  - pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  unittests:
    strategy:
      matrix:
        python-version: [ '3.12' ]
    name: Unit Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: SanctumLabs/ci-workflows/.github/workflows/python-test-with-postgres.yml@main
    with:
      command: make test
      python-version: ${{ matrix.python-version }}
      packager: poetry
      database-name: dbkit-sql
      database-username: sanctumlabs
      database-password: sanctumlabs
      database-port: 5432
