name: Tests

on:
  workflow_run:
    workflows:
      - "Lint"
    types:
      - completed

permissions:
  contents: read
  pull-requests: read

jobs:
  unittests:
    name: Unit Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        python-version: [ '3.12' ]
    services:
      postgres:
        image: postgres:16.2-alpine
        env:
          POSTGRES_DB: dbkit-sql
          POSTGRES_USER: sanctumlabs
          POSTGRES_PASSWORD: sanctumlabs
        ports:
          - 5432:5432
    steps:
      - name: Run Tests
        uses: SanctumLabs/ci-workflows/.github/workflows/python-test.yml@main
        with:
          command: make test
          python-version: ${{ matrix.python-version }}
          packager: poetry
